/**
 * OpenCatan Redux State Management
 *
 * This module exports all Redux store components for the OpenCatan game.
 *
 * Store Structure:
 * - game: Core game state (phase, turn, settings, dice)
 * - board: Board state (tiles, buildings, roads, robber/pirate/merchant)
 * - players: Player state (resources, cards, achievements)
 * - lobby: Pre-game lobby state (room code, player list, settings)
 * - ui: UI state (modals, selections, audio settings, hover states)
 * - log: Game log and chat messages
 */

// Store
export { store, type RootState, type AppDispatch, type AppThunk } from './store';

// Game Slice
export {
  default as gameReducer,
  // Actions
  setPhase,
  nextTurn,
  setCurrentPlayer,
  updateTimer,
  tickTimer,
  startGame,
  setDiceRoll,
  setLongestRoad,
  setLargestArmy,
  updateBank,
  addToBank,
  removeFromBank,
  setPendingDiscard,
  removePendingDiscard,
  setDevCardPlayedThisTurn,
  decrementDevDeck,
  decrementProgressDeck,
  advanceBarbarian,
  resetBarbarian,
  setBarbarianStrength,
  setTotalKnightStrength,
  setWinner,
  updateSettings as updateGameSettings,
  updateSetupPhase,
  setRoadBuildingRemaining,
  setYearOfPlentyRemaining,
  resetGame,
  // Selectors
  selectPhase,
  selectTurn,
  selectCurrentPlayerId,
  selectTurnTimeRemaining,
  selectTurnStartedAt,
  selectGameMode,
  selectGameSettings,
  selectLastRoll,
  selectDiceTotal,
  selectLongestRoad as selectGameLongestRoad,
  selectLargestArmy as selectGameLargestArmy,
  selectDevDeckCount,
  selectBank,
  selectPendingDiscard,
  selectDevCardPlayedThisTurn,
  selectProgressDecks,
  selectBarbarianPosition,
  selectBarbarianStrength,
  selectTotalKnightStrength,
  selectWinnerId,
  selectFinalScores,
  selectIsGameOver,
  selectSetupPhase,
  selectRoadBuildingRemaining,
  selectYearOfPlentyRemaining,
  selectIsSetupPhase,
  selectBarbarianNearAttack,
  selectBankResource,
  selectSetupState,
  selectSetupPlacementIndex,
  selectLastPlacedSettlement,
  selectSetupPlayerPlacements,
  selectIsSetupComplete,
  // Setup actions
  setSetupState,
  updateSetupState,
  setLastPlacedSettlement,
  incrementSetupPlacementIndex,
  updatePlayerSetupPlacements,
  completeSetup,
  // Types
  type GameSliceState,
  type SetupStateData,
} from './slices/gameSlice';

// Board Slice
export {
  default as boardReducer,
  // Actions
  setTiles,
  updateTile,
  setPorts,
  placeBuilding,
  upgradeToCity,
  addCityWall,
  setMetropolis,
  pillageCity,
  removeBuilding,
  placeRoad,
  moveShip,
  removeRoad,
  moveRobber,
  movePirate,
  setMerchant,
  placeKnight,
  updateKnight,
  moveKnight,
  removeKnight,
  deactivateAllKnights,
  resetKnightTurnFlags,
  revealFogTile,
  syncBoard,
  resetBoard,
  // Selectors
  selectTiles,
  selectBuildings,
  selectRoads,
  selectPorts,
  selectKnights,
  selectRobberLocation,
  selectPirateLocation,
  selectMerchantLocation,
  selectTileAt,
  selectBuildingAt,
  selectRoadAt,
  selectRoadsForPlayer,
  selectBuildingsForPlayer,
  selectSettlementsForPlayer,
  selectCitiesForPlayer,
  selectKnightsForPlayer,
  selectActiveKnightsForPlayer,
  selectTilesWithNumber,
  selectKnightAt,
  selectPlayerKnightStrength,
  selectPlayerPorts,
  selectIsVertexOccupied,
  selectIsEdgeOccupied,
  // Types
  type BoardSliceState,
} from './slices/boardSlice';

// Players Slice
export {
  default as playersReducer,
  // Actions
  setPlayers,
  addPlayer,
  removePlayer,
  updatePlayer,
  setPlayerConnected,
  setTurnOrder,
  updatePlayerResources,
  addResources,
  removeResources,
  updateCommodities,
  addCommodities,
  addCard,
  removeCard,
  markCardPlayed,
  addProgressCard,
  removeProgressCard,
  updateCityImprovements,
  upgradeCityImprovement,
  updatePieceCount,
  updateLongestRoadLength,
  incrementArmySize,
  incrementTimesRobbed,
  incrementTimesWasRobbed,
  incrementTradesMade,
  resetTurnFlags,
  transferHost,
  syncPlayers,
  resetPlayers,
  // Selectors
  selectPlayers,
  selectTurnOrder,
  selectCurrentPlayer,
  selectPlayerById,
  selectPlayerResources,
  selectPlayerCommodities,
  selectPlayerDevCards,
  selectPlayerProgressCards,
  selectPlayerCardCount,
  selectPlayerResourceCount,
  selectPlayerCommodityCount,
  selectPlayerHandSize,
  selectHostPlayer,
  selectConnectedPlayers,
  selectCanAfford,
  selectTradeRatio,
  selectPlayableDevCards,
  selectCanPlayDevCard,
  // Types
  type PlayersSliceState,
} from './slices/playersSlice';

// Lobby Slice
export {
  default as lobbyReducer,
  // Actions
  setRoomCode,
  setLocalPlayerId,
  addPlayer as addLobbyPlayer,
  removePlayer as removeLobbyPlayer,
  updatePlayer as updateLobbyPlayer,
  setReady,
  setPlayerColor,
  setSettings as updateLobbySettings,
  setLocalPlayer,
  setConnectionStatus,
  setErrorMessage,
  startGame as startLobbyGame,
  transferHost as transferLobbyHost,
  setPlayerConnected as setLobbyPlayerConnected,
  syncLobbyState,
  resetLobby,
  // Selectors
  selectRoomCode,
  selectLobbyPlayers,
  selectLocalPlayerId,
  selectIsHost,
  selectGameStarted,
  selectLobbySettings,
  selectAvailableColors,
  selectConnectionStatus,
  selectErrorMessage,
  selectLocalLobbyPlayer,
  selectAllPlayersReady,
  selectHasMinimumPlayers,
  selectCanAddMorePlayers,
  selectLobbyHost,
  selectCanStartGame,
  selectConnectedPlayersCount,
  selectLobbyPlayerById,
  // Types
  type LobbySettings,
  type LobbyState,
} from './slices/lobbySlice';

// UI Slice
export {
  default as uiReducer,
  // Actions
  setBuildMode,
  setSelectedHex,
  setSelectedAction,
  clearSelectedAction,
  openTradeModal,
  closeTradeModal,
  setPendingTrade,
  updatePendingTrade,
  addIncomingTradeOffer,
  updateIncomingTradeOffer,
  removeIncomingTradeOffer,
  clearIncomingTradeOffers,
  openModal,
  closeModal,
  toggleSound,
  setSoundEnabled,
  setVolume,
  addToast,
  removeToast,
  clearToasts,
  toggleBuildCosts,
  toggleDiceStats,
  toggleCompactPlayerPanels,
  setFullscreen,
  setZoomLevel,
  zoomIn,
  zoomOut,
  resetZoom,
  setHoveredHex,
  setHoveredVertex,
  setHoveredEdge,
  setLoading,
  resetUi,
  // Selectors
  selectBuildMode,
  selectSelectedHex,
  selectSelectedAction,
  selectTradeModalOpen,
  selectPendingTrade,
  selectIncomingTradeOffers,
  selectModal,
  selectToasts,
  selectSoundEnabled,
  selectVolume,
  selectShowBuildCosts,
  selectShowDiceStats,
  selectCompactPlayerPanels,
  selectIsFullscreen,
  selectZoomLevel,
  selectHoveredHex,
  selectHoveredVertex,
  selectHoveredEdge,
  selectIsLoading,
  selectLoadingMessage,
  selectIsModalOpen,
  selectIsModalType,
  selectIsBuildMode,
  selectHasPendingTradeOffers,
  selectPendingTradeOffersCount,
  // Types
  type BuildMode,
  type SelectedAction,
  type ModalType,
  type ModalState,
  type ToastMessage,
  type UISliceState,
} from './slices/uiSlice';

// Log Slice
export {
  default as logReducer,
  // Factory helpers
  createLogEntry,
  createChatMessage,
  // Actions
  addLogEntry,
  addLogEntries,
  addChatMessage,
  clearLog,
  clearChat,
  syncLog,
  resetLog,
  // Selectors
  selectLog,
  selectChat,
  selectVisibleLog,
  selectRecentLog,
  selectLogForTurn,
  selectLogByType,
  selectRecentChat,
  selectDiceHistory,
  selectDiceStats,
  selectTradeHistory,
  selectLogForPlayer,
  selectResourceGainsLog,
  selectRobberLog,
  // Types
  type LogSliceState,
} from './slices/logSlice';

// Stats Slice
export {
  default as statsReducer,
  // Actions
  recordDiceRoll,
  recordResourceGain,
  recordTrade,
  recordBuild,
  recordDevCardAction,
  recordRobberMove,
  recordKnightPlayed,
  updateLongestRoadAchieved,
  setGameStartTime,
  setGameEndTime,
  initializePlayerStats,
  syncStats,
  resetStats,
  // Selectors
  selectDiceRolls,
  selectRollCounts,
  selectResourcesCollected,
  selectTrades as selectStatsTradeRecords,
  selectBuilds,
  selectDevCardActions,
  selectRobberMoves,
  selectGameStartTime,
  selectGameEndTime,
  selectKnightsPlayed,
  selectLongestRoadAchieved,
  selectTotalTurns,
  selectMostCommonRoll,
  selectGameDuration,
  selectTotalResourcesCollected,
  selectTotalTradesCompleted,
  selectTotalDevCardsBought,
  selectPlayerResourcesCollected,
  selectPlayerTotalResourcesCollected,
  selectPlayerTrades,
  selectPlayerBuilds,
  selectPlayerBuildCounts,
  // Types
  type StatsSliceState,
  type TradeRecord,
  type BuildRecord,
  type DevCardRecord,
} from './slices/statsSlice';

// Trade Slice
export {
  default as tradeReducer,
  // Actions
  addOutgoingOffer,
  addIncomingOffer,
  updateOutgoingOfferStatus,
  updateIncomingOfferStatus,
  addDeclinedBy,
  addCounterOffer,
  removeOutgoingOffer,
  removeIncomingOffer,
  setActiveCounterOffer,
  clearActiveCounterOffer,
  clearOffersFromPlayer,
  expireOldOffers,
  clearAllOffers,
  resetTrade,
  // Selectors
  selectOutgoingOffers,
  selectIncomingOffers,
  selectActiveCounterOffer,
  selectDefaultTimeout,
  selectActiveOutgoingOffers,
  selectActiveIncomingOffers,
  selectPendingIncomingOffers,
  selectCounterOffersForOffer,
  selectHasPendingIncomingOffers,
  selectPendingIncomingOffersCount,
  // Types
  type TradeSliceState,
  type TradeOfferExtended,
  type TradeOfferStatus,
} from './slices/tradeSlice';
